import{a as q,S as v,i as l}from"./assets/vendor-hwdYKDic.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const E="48830775-40ff68ea61f2bc47ba43ee541",S="https://pixabay.com/api/",P=40;async function m(r,e){const i=`${S}?key=${E}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&per_page=${P}`;try{return(await q.get(i)).data}catch(n){throw console.error("Error fetching data from Pixabay API:",n),n}}function u(r,e=!1){const i=document.querySelector(".gallery");e&&(i.innerHTML="");const n=r.map(({largeImageURL:o,webformatURL:c,tags:p,likes:y,views:L,comments:b,downloads:w})=>`
      <a href="${o}" class="gallery-item">
        <img src="${c}" alt="${p}" />
        <div class="image-info">
          <p class="image-title"><strong>Likes:</strong> ${y}</p>
          <p class="image-title"><strong>Views:</strong> ${L}</p>
          <p class="image-title"><strong>Comments:</strong> ${b}</p>
          <p class="image-title"><strong>Downloads:</strong> ${w}</p>
        </div>
      </a>`).join("");i.insertAdjacentHTML("beforeend",n),new v(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:1,showCounter:!1}).refresh()}function $(){var e;const r=((e=document.querySelector(".gallery-item"))==null?void 0:e.getBoundingClientRect().height)||100;window.scrollBy({top:r*2,behavior:"smooth"})}const a={form:document.querySelector(".search-form"),input:document.querySelector(".search-input"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-btn")},s={query:"",page:1,totalHits:0};function f(){a.loader.classList.remove("hidden")}function d(){a.loader.classList.add("hidden")}function h(){a.loadMoreBtn.classList.remove("hidden")}function g(){a.loadMoreBtn.classList.add("hidden")}a.form.addEventListener("submit",async r=>{if(r.preventDefault(),s.query=a.input.value.trim(),s.page=1,!s.query){l.error({title:"Error",message:"Please enter a search term!",position:"topRight",timeout:2e3}),a.input.value="",u([],!0);return}f(),g();try{const{hits:e,totalHits:i}=await m(s.query,s.page);s.totalHits=i,d(),u([],!0),e.length===0?l.info({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}):(u(e,!0),e.length<s.totalHits&&h())}catch(e){d(),l.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),u([],!0),console.error("Error fetching images:",e)}});a.loadMoreBtn.addEventListener("click",async()=>{s.page+=1,g(),f();try{const{hits:r}=await m(s.query,s.page);if(d(),r.length===0){l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3});return}u(r,!1),$(),r.length<40?(g(),l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"bottomRight",timeout:3e3})):h()}catch(r){d(),l.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),console.error("Error fetching images:",r)}});
//# sourceMappingURL=index.js.map
